import os
import requests
import pandas as pd

API_KEY = os.environ.get("CFBD_API_KEY")
YEAR = 2025

print("Loaded API KEY:", "YES" if API_KEY else "NO")

headers = {"Authorization": f"Bearer {API_KEY}"}

# -------------------------------------------------------
# Load fbs_teams.csv (conference mapping)
# -------------------------------------------------------
teams_path = "fbs_teams.csv"
if not os.path.exists(teams_path):
    raise FileNotFoundError("Missing fbs_teams.csv for conference mapping!")

fbs_teams = pd.read_csv(teams_path)

# Build mapping: school → conference
conference_map = dict(zip(fbs_teams["school"], fbs_teams["conference"]))

# -------------------------------------------------------
# Helper: Fetch CFBD API with debug printing
# -------------------------------------------------------
def fetch_cfbd(url, label):
    print(f"\nRequesting {label} from {url}")

    r = requests.get(url, headers=headers)

    print("Status:", r.status_code)
    print("Response text (first 300 chars):")
    print(r.text[:300])

    if r.status_code != 200:
        raise RuntimeError(f"CFBD error fetching {label}: {r.status_code}")

    try:
        return pd.DataFrame(r.json())
    except Exception:
        print(f"❌ JSON decode failure for {label}")
        print("Raw response:")
        print(r.text)
        raise


# -------------------------------------------------------
# Fetch raw penalties
# -------------------------------------------------------
raw_url = f"https://api.collegefootballdata.com/penalties?year={YEAR}"
raw_penalties = fetch_cfbd(raw_url, "raw penalties")

# Normalize team column
raw_penalties["team"] = raw_penalties["team"].fillna(raw_penalties.get("committer"))
raw_penalties["team"] = raw_penalties["team"].fillna(raw_penalties.get("drawn_team"))

# Add conference
raw_penalties["conference"] = raw_penalties["team"].map(conference_map)

raw_penalties.to_csv("penalties_2025_FBS_raw_with_meta.csv", index=False)
print("Saved: penalties_2025_FBS_raw_with_meta.csv")

# -------------------------------------------------------
# Build committed weekly
# -------------------------------------------------------
committed_weekly = raw_penalties.rename(columns={"committer": "team"})
committed_weekly = committed_weekly[["week", "team", "penalty_type", "penalty_category",
                                     "total_penalties", "total_yards", "avg_yards_per_penalty"]]
committed_weekly["conference"] = committed_weekly["team"].map(conference_map)

committed_weekly.to_csv("penalties_2025_FBS_committed_weekly.csv", index=False)
print("Saved: penalties_2025_FBS_committed_weekly.csv")

# -------------------------------------------------------
# Build drawn weekly
# -------------------------------------------------------
drawn_weekly = raw_penalties.rename(columns={"drawn_team": "team"})
drawn_weekly = drawn_weekly[["week", "team", "penalty_type", "penalty_category",
                             "total_penalties", "total_yards", "avg_yards_per_penalty"]]
drawn_weekly["conference"] = drawn_weekly["team"].map(conference_map)

drawn_weekly.to_csv("penalties_2025_FBS_drawn_weekly.csv", index=False)
print("Saved: penalties_2025_FBS_drawn_weekly.csv")

# -------------------------------------------------------
# Build season totals by team/type
# -------------------------------------------------------
# Committed season
committed_season = committed_weekly.groupby(
    ["team", "penalty_type", "penalty_category", "conference"],
    as_index=False
).agg({
    "total_penalties": "sum",
    "total_yards": "sum",
})

committed_season["avg_yards_per_penalty"] = (
    committed_season["total_yards"] / committed_season["total_penalties"]
).round(2)

committed_season.to_csv("penalties_2025_FBS_committed_season.csv", index=False)
print("Saved: penalties_2025_FBS_committed_season.csv")

# Drawn season
drawn_season = drawn_weekly.groupby(
    ["team", "penalty_type", "penalty_category", "conference"],
    as_index=False
).agg({
    "total_penalties": "sum",
    "total_yards": "sum",
})

drawn_season["avg_yards_per_penalty"] = (
    drawn_season["total_yards"] / drawn_season["total_penalties"]
).round(2)

drawn_season.to_csv("penalties_2025_FBS_drawn_season.csv", index=False)
print("Saved: penalties_2025_FBS_drawn_season.csv")

# -------------------------------------------------------
# Merge AP & CFP rankings
# -------------------------------------------------------

# Load latest ranking snapshot (already generated by your pipeline)
if os.path.exists("penalties_2025_fbs_latest_week_pivot.csv"):
    poll_df = pd.read_csv("penalties_2025_fbs_latest_week_pivot.csv")
    committed_season = committed_season.merge(
        poll_df[["school", "AP Top 25", "CFP"]],
        left_on="team",
        right_on="school",
        how="left"
    ).drop(columns=["school"])
    drawn_season = drawn_season.merge(
        poll_df[["school", "AP Top 25", "CFP"]],
        left_on="team",
        right_on="school",
        how="left"
    ).drop(columns=["school"])
else:
    print("⚠ No poll file found — skipping AP/CFP merge")

committed_season.to_csv("penalties_2025_FBS_committed_season_with_rankings.csv", index=False)
drawn_season.to_csv("penalties_2025_FBS_drawn_season_with_rankings.csv", index=False)

print("Done!")
